using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class UISetActive : MonoBehaviour
{
    public GameObject ゴ}UI;

    public bool L兵ン, 具BjK, 干;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if(L兵ン)
        {
            if (GameManager.UI}闽)
            {
                ゴ}UI.SetActive(true);
            }
            else if (!GameManager.UI}闽)
            {
                ゴ}UI.SetActive(false);
            }
        }    
        
        if (具BjK)
        {
            if (GameManager.局Τもj || GameManager.局ΤBj)
            {
                if (GameManager.UI}闽)
                {
                    ゴ}UI.SetActive(true);
                }
                else if (!GameManager.UI}闽)
                {
                    ゴ}UI.SetActive(false);
                }
            }

            if (!GameManager.局Τもj && !GameManager.局ΤBj)
            {
                ゴ}UI.SetActive(false);
            }
        }

        if (干)
        {
            if (GameManager.局Τ干)
            {
                if (GameManager.UI}闽)
                {
                    ゴ}UI.SetActive(true);
                }
                else if (!GameManager.UI}闽)
                {
                    ゴ}UI.SetActive(false);
                }
            }

            if (!GameManager.局Τ干)
            {
                ゴ}UI.SetActive(false);
            }
            
        }

    }
}
