using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;


public class AmmoTMP : MonoBehaviour
{
    public TextMeshProUGUI lu;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        lu = transform.GetComponent<TextMeshProUGUI>();

        if(Gun_fire.ち传Z竟s腹 == 0)//もj
        {
            string Y搔^Xlu计q = Gun_fire.lu.ToString();

            // Nゅr]wUI Texttext妮┦
            lu.text = Y搔^Xlu计q;
        }

        if (Gun_fire.ち传Z竟s腹 == 1)//Bj
        {
            string Y搔^Xlu计q = Gun_fire.rifleAmmo.ToString();

            // Nゅr]wUI Texttext妮┦
            lu.text = Y搔^Xlu计q;
        }

    }
}
