using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Bloodspray_Effect : MonoBehaviour
{
    public static Bloodspray_Effect D北;

    public int Q寮痞r = 0;

    private Animator anim;

    // Start is called before the first frame update
    void Start()
    {
        D北 = this;

        anim = GetComponent<Animator>();
    }

    // Update is called once per frame
    void Update()
    {
        Q寮痞r = PlayerHealth1.BloodI;
    }

    public void H诀铬宓e()
    {
        //anim.Play("菥");
        switch (Q寮痞r)
        {
            case 1: // QUIT
                anim.Play("陪1");
                break;

            case 2: //CLEAR
                anim.Play("陪2");
                break;

            case 3: //CLEAR
                anim.Play("陪3");
                break;

            default:

                break;
        }
    }
}
